const STOPWORDS = new Set("a an and or of for to with without the unit units device devices machine machines equipment set sets system systems medical hospital portable mobile digital manual electric electrical adult paediatric pediatric infant neonatal new room bay ed emergency".split(" "));
const ALIASES = {
  alarm:["alarms","warning","alert","bell","buzzer","indicator"], bell:["alarm","alarms","alert","buzzer","warning"], buzzer:["alarm","alarms","alert","bell","warning"], alert:["alarm","alarms","warning","indicator"],
  bp:["blood pressure","sphygmomanometer","cuff","nibp"], nibp:["blood pressure","sphygmomanometer","cuff"], spo2:["pulse oximeter","oximeter","oxygen saturation"], sats:["pulse oximeter","oximeter","oxygen saturation"],
  ecg:["ekg","electrocardiograph","cardiac monitor","heart monitor"], ekg:["ecg","electrocardiograph","cardiac monitor","heart monitor"], defib:["defibrillator","defibrillator monitor","cardiac resuscitation"], aed:["defibrillator","automated external defibrillator"],
  monitor:["physiologic monitoring","vital signs","cardiac monitor","patient monitor"], vital:["physiologic monitoring","patient monitor","heart rate","respiration","temperature"],
  ventilator:["ventilation","respirator","breathing support","pulmonary"], respirator:["ventilator","ventilation","breathing support","pulmonary"], ambu:["manual resuscitator","resuscitator","bag valve mask","bvm"], bvm:["manual resuscitator","resuscitator","bag valve mask"],
  suction:["aspirator","vacuum","suction regulator"], vacuum:["suction","aspirator"], oxygen:["o2","oxygen administration","oxygen concentrator","oxygen analyzer","oxygen regulator"], o2:["oxygen","oxygen administration"],
  nebuliser:["nebulizer","aerosol"], nebulizer:["nebuliser","aerosol"], drip:["infusion","intravenous","iv"], iv:["intravenous","infusion","catheter","cannula"], syringe:["injector","infusion pump"], pump:["infusion","syringe pump","enteral feeding pump"],
  laryngoscope:["airway","intubation","laryngoscopy"], intubation:["laryngoscope","airway","endotracheal"], stretcher:["trolley","gurney","mobile stretcher","patient transport"], gurney:["stretcher","trolley","patient transport"], trolley:["cart","stretcher","patient transport"], cart:["trolley","resuscitation cart","medication cart"],
  wheelchair:["chair","patient transport","mobility"], autoclave:["steam sterilizer","sterilizing unit","sterilization"], sterilizer:["sterilising","sterilizing","autoclave","steam"], fridge:["refrigerator","cold storage"], freezer:["refrigerator","cold storage"],
  ultrasound:["sonography","scanner","ultrasonic"], usg:["ultrasound","sonography","ultrasonic"], xray:["radiographic","radiology","x ray"], ct:["computed tomography","scanner"], glucose:["blood glucose","analyzer","monitor"], glucometer:["blood glucose","analyzer","monitor"],
  thermometer:["temperature","probe"], temperature:["thermometer","probe","monitor"], cabinet:["storage","medicine cabinet","instrument cabinet"], light:["lamp","examination light","surgical light"], lamp:["light","examination light","surgical light"], bed:["patient bed","electric bed","hospital bed"], mattress:["bed","pressure pad"]
};
const CATEGORY_HINTS = [
  {q:["airway","intubation","laryngoscope","ventilator","respirator","oxygen","ambu","bvm","nebulizer","nebuliser","suction","mask","cpap"], t:["airway","laryngoscope","ventilation","resuscitator","pulmonary","oxygen","nebulizer","aspirator","suction","mask","continuous positive airway"], boost:18, name:"airway/breathing"},
  {q:["ecg","ekg","cardiac","heart","defib","aed","monitor","vital","bp","nibp","spo2","oximeter"], t:["electrocardiograph","ecg","cardiac","defibrillator","monitor","heart","oximeter","sphygmomanometer","physiologic"], boost:20, name:"cardiac/monitoring"},
  {q:["infusion","syringe","pump","drip","iv","intravenous","injector","cannula","catheter"], t:["infusion","syringe","pump","intravenous","injector","cannula","catheter","administration set"], boost:18, name:"infusion/injection"},
  {q:["bed","stretcher","trolley","gurney","cart","wheelchair","chair","table","mattress"], t:["bed","stretcher","cart","chair","wheelchair","mattress","support"], boost:12, name:"transport/furniture"},
  {q:["xray","radiology","radiographic","ultrasound","usg","scanner","ct","mri","scope","endoscope"], t:["radiographic","scanner","computed tomography","ultrasound","ultrasonic","scope","endoscope"], boost:16, name:"imaging/diagnostic"},
  {q:["sterile","sterilizer","steriliser","autoclave","disinfect","washer","cleaner"], t:["sterilizing","sterilization","disinfector","washer","cleaner","germicide"], boost:16, name:"sterile/cleaning"},
  {q:["cabinet","rack","storage","fridge","refrigerator","freezer","medicine","instrument"], t:["cabinet","rack","refrigerator","medicine","instrument","storage"], boost:10, name:"storage/general"}
];
let DB = [];
const qEl = document.getElementById('q'), resultsEl = document.getElementById('results'), statusEl = document.getElementById('status');
function normalize(s){ return String(s||'').toLowerCase().replaceAll('x-ray','xray').replaceAll('x ray','xray').replaceAll('e.c.g','ecg').replaceAll('e.k.g','ekg').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim(); }
function stem(tok){ tok=normalize(tok); if(tok.length>4&&tok.endsWith('ies'))return tok.slice(0,-3)+'y'; if(tok.length>5&&tok.endsWith('ing'))return tok.slice(0,-3); if(tok.length>4&&tok.endsWith('es'))return tok.slice(0,-2); if(tok.length>3&&tok.endsWith('s'))return tok.slice(0,-1); return tok; }
function tokens(s){ return normalize(s).split(' ').filter(x=>x&&!STOPWORDS.has(x)); }
function expandQuery(q){ const base=normalize(q), parts=[base]; for(const tok of base.split(' ')){ if(ALIASES[tok]) parts.push(...ALIASES[tok]); } return normalize(parts.join(' ')); }
function ratio(a,b){ if(!a||!b)return 0; const m=a.length,n=b.length; const dp=Array.from({length:m+1},()=>Array(n+1).fill(0)); for(let i=0;i<=m;i++)dp[i][0]=i; for(let j=0;j<=n;j++)dp[0][j]=j; for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1)); return 1-(dp[m][n]/Math.max(m,n)); }
function parseCSV(text){ const rows=[]; let i=0, row=[], val='', quote=false; while(i<text.length){ const c=text[i]; if(quote){ if(c==='"'&&text[i+1]==='"'){val+='"';i++;} else if(c==='"') quote=false; else val+=c; } else { if(c==='"') quote=true; else if(c===','){row.push(val);val='';} else if(c==='\n'){row.push(val); rows.push(row); row=[]; val='';} else if(c!=='\r') val+=c; } i++; } if(val||row.length){row.push(val);rows.push(row);} return rows; }
function score(q,item){ const qn=normalize(q), qe=expandQuery(q), qt=new Set(tokens(qe)), raw=new Set(tokens(q)), qst=new Set([...qt].map(stem)); let score=0, reasons=[]; if(qn && item.norm.includes(qn)){score+=45; reasons.push('direct phrase');} if(item.norm && qe.includes(item.norm)){score+=45; reasons.push('term phrase');}
  const overlap=[...qst].filter(x=>item.stems.has(x)); if(overlap.length){ score += 18*overlap.length + Math.min(12, 18*overlap.length/Math.max(qst.size,1)); reasons.push('keyword: '+overlap.slice(0,4).join(', ')); }
  let aliasHit=0; for(const r of raw){ for(const a of (ALIASES[r]||[])){ if(item.norm.includes(normalize(a))){aliasHit++; break;} } } if(aliasHit){score+=14*aliasHit; reasons.push('related keyword');}
  for(const cat of CATEGORY_HINTS){ if(cat.q.some(x=>qe.includes(x)) && cat.t.some(x=>item.norm.includes(x))){ score+=cat.boost; reasons.push(cat.name); } }
  if(qn.length>=3){ const fr=ratio(qn,item.norm); if(fr>0.55){score+=fr*18; reasons.push('fuzzy phrase');} else { let best=0; for(const a of qst){ for(const b of item.stems){ best=Math.max(best,ratio(a,b)); } } if(best>0.78){score+=best*12; reasons.push('fuzzy word');} } }
  return {score, reasons:[...new Set(reasons)].slice(0,3).join('; ')}; }
function search(){ const q=qEl.value.trim(); if(!q){ resultsEl.innerHTML='<div class="empty">Start typing to search UMDNS codes.</div>'; statusEl.textContent=`${DB.length} UMDNS terms loaded`; return; }
  const qst=new Set(tokens(expandQuery(q)).map(stem)); let candidates=DB.filter(x=>[...qst].some(t=>x.search.includes(' '+t+' ')||x.norm.includes(t))); if(candidates.length<30) candidates=DB;
  const ranked=candidates.map(x=>({...x,...score(q,x)})).filter(x=>x.score>8).sort((a,b)=>b.score-a.score).slice(0,50);
  statusEl.textContent = `${ranked.length} result${ranked.length===1?'':'s'} for “${q}”`;
  if(!ranked.length){ resultsEl.innerHTML='<div class="empty">No strong match found. Try a broader term such as “alarm”, “monitor”, “oxygen”, or “suction”.</div>'; return; }
  resultsEl.innerHTML = ranked.map(r=>`<div class="row"><div class="code">${r.code}</div><div><div class="term">${escapeHtml(r.term)}</div><div class="reason">${escapeHtml(r.reasons||'ranked match')}</div></div><div class="score">${Math.round(r.score)}</div></div>`).join(''); }
function escapeHtml(s){ return String(s).replace(/[&<>"']/g, m=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[m])); }
let raf=0; qEl.addEventListener('input',()=>{ cancelAnimationFrame(raf); raf=requestAnimationFrame(search); }); document.getElementById('clearBtn').onclick=()=>{qEl.value=''; qEl.focus(); search();};
fetch('umdns_codes.csv').then(r=>r.text()).then(text=>{ const rows=parseCSV(text).slice(1); DB=rows.map(r=>{ const code=(r[0]||'').trim(), term=(r[1]||'').trim(), norm=normalize(term), toks=new Set(tokens(term)), stems=new Set([...toks].map(stem)); return {code,term,norm,tokens:toks,stems,search:' '+norm+' '+[...stems].join(' ')+' '}; }).filter(x=>x.code&&x.term); search(); }).catch(err=>{statusEl.textContent='Could not load umdns_codes.csv'; resultsEl.innerHTML='<div class="empty">Database file could not be loaded. Make sure umdns_codes.csv is in the same folder as index.html.</div>';});
